name: Combined Workflow

on:
  push:
  schedule:
    - cron: "20 5 * * *"
  workflow_dispatch:

jobs:
  blog-post-update:
    name: Blog Post Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://codercops.tech/feed.xml"

  github-activity-update:
    name: GitHub Activity Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        with:
          COMMIT_MSG: "Update README with the recent activity"
          MAX_LINES: 10
          COMMIT_NAME: GitHub Activity Readme

  stackoverflow-activity-update:
    name: StackOverflow Activity Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "STACKOVERFLOW"
          commit_message: "Updated readme with the latest stackOverflow data"
          feed_list: "https://stackoverflow.com/feeds/user/16866182"
          template: "<tr><td>$title</td><td>$url</td></tr>"

  waka-stats-update:
    name: Waka Stats Update
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUBTOKEN }}
          SHOW_PROFILE_VIEWS: False

  waka-readme-update:
    name: Waka Readme Update
    runs-on: ubuntu-latest
    steps:
      - uses: guilyx/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUBTOKEN }}
          SECTION_NAME: "waka-simple"
          COMMIT_MESSAGE: "Updated simple waka stats section"
          BLOCKS: "⣀⣄⣤⣦⣶⣷⣿"
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          SHOW_TITLE: true
