name: StackOverflow Activity Update

on:
  schedule:
    - cron: "20 5 * * *"
  workflow_dispatch:

jobs:
  stackoverflow_activity_update:
    name: 📚 StackOverflow Activity Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Update README with StackOverflow Activity
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "STACKOVERFLOW"
          commit_message: "Updated readme with the latest stackOverflow data"
          feed_list: "https://stackoverflow.com/feeds/user/16866182"
          template: "<tr><td>$title</td><td>$url</td></tr>"
